# Generated by Django 2.2.4 on 2020-11-25 10:58

from django.db import migrations


def is_new_building(apps, schema_editor):

    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()

    for flat in flats:
        flat.new_building = flat.construction_year >= 2015
        flat.save()


def move_backward(apps, schema_editor):

    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()

    for flat in flats:
        flat.new_building = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(is_new_building, move_backward)
    ]
