# Generated by Django 2.2.4 on 2020-11-30 17:10

from django.db import migrations
import phonenumbers


def phone_parser(apps, schema_editor):

    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()

    for flat in flats:
        number_parsed = phonenumbers.parse(flat.owners_phonenumber, "RU")
        if phonenumbers.is_valid_number(number_parsed):
            pure_phone = phonenumbers.format_number(number_parsed, phonenumbers.PhoneNumberFormat.E164)
            flat.owner_pure_phone = pure_phone
        else:
            flat.owner_pure_phone= 'Incorrect number'
        flat.save()


def move_backward(apps, schema_editor):

    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()

    for flat in flats:
        flat.owner_pure_phone = None
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20201130_2009'),
    ]

    operations = [
        migrations.RunPython(phone_parser, move_backward)
    ]


