# Generated by Django 2.2.4 on 2020-12-01 10:46

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20201130_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complain_text',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Текст жалобы'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.NullBooleanField(db_index=True, verbose_name='Новостройка'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='owner',
            field=models.CharField(db_index=True, max_length=200, verbose_name='ФИО владельца'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='owners_phonenumber',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Номер владельца'),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(db_index=True, max_length=200, null=True, verbose_name='ФИО владельца')),
                ('owners_phonenumber', models.CharField(db_index=True, max_length=20, null=True, verbose_name='Номер владельца')),
                ('owner_pure_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True, region=None, verbose_name='Нормализованный номер владельца')),
                ('owner_flats', models.ManyToManyField(db_index=True, related_name='flats_of_owner', to='property.Flat', verbose_name='Квартиры в собственности')),
            ],
        ),
    ]
