# Generated by Django 2.2.4 on 2020-12-01 10:48

from django.db import migrations


def load_owners(apps, schema_editor):

    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()

    for flat in flats:
        Owner.objects.get_or_create(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone,
        )


def move_backward(apps, schema_editor):

    Owner = apps.get_model('property', 'Owner')
    owners = Owner.objects.all()
    owners.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20201201_1346'),
    ]

    operations = [
        migrations.RunPython(load_owners, move_backward)
    ]
