# Generated by Django 2.2.4 on 2020-12-04 21:18

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20201201_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='owner_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                db_index=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name='Нормализованный номер владельца'),
        ),
    ]
